import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter, Style_Script } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import "./theme-config.css";
import AuthProvider from "./auth/Provider";
import Container from "./components/Container";
import QueryClientProvider from "./QueryClient";
import Script from "next/script";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-8LZKXM5VQ3"
          strategy="afterInteractive"
        />
        <Script
          id="google-analytics"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-8LZKXM5VQ3');
            `,
          }}
        />
      </head>
      <body className={inter.variable}>
        <AuthProvider>
          <QueryClientProvider>
            <Theme accentColor="iris">
              <Navbar></Navbar>
              <main className="p-5">
                <Container> {children}</Container>
              </main>
            </Theme>
          </QueryClientProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
